version: 2


updates:
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 3

    labels:
      - "dependencies"
      - "python"

    reviewers:
      - "nakhan-sonata-afk"

    commit-message:
      prefix: "deps"
      include: "scope"

    groups:
      python-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "UTC"

    open-pull-requests-limit: 3

    labels:
      - "dependencies"
      - "github-actions"

    reviewers:
      - "nakhan-sonata-afk"

    commit-message:
      prefix: "ci"
      include: "scope"