name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test.txt

    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q

  quality:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install quality dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/quality.txt

    - name: Run quality checks
      run: |
        python -m pycodestyle edx_filters_pipelines tests *.py
        python -m pydocstyle edx_filters_pipelines tests *.py
        python -m isort --check-only --diff edx_filters_pipelines tests *.py
        python -m pylint edx_filters_pipelines --rcfile=pylintrc
